-- MySQL Script generated by MySQL Workbench
-- 03/28/18 17:16:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fname` VARCHAR(45) NOT NULL COMMENT '',
  `lname` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `photo` VARCHAR(45) NULL COMMENT '',
  `country` VARCHAR(45) NOT NULL COMMENT '',
  `city` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `status` ENUM('Active', 'Blocked') NOT NULL COMMENT '',
  `level` INT NULL COMMENT '',
  `available` TINYINT(1) NOT NULL COMMENT '',
  `Type` ENUM('Normal', 'PreExpert', 'Expert') NULL COMMENT '',
  `bankaccount` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  UNIQUE INDEX `code_UNIQUE` (`code` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`language_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language_has_User` (
  `language_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`language_id`, `user_id`)  COMMENT '',
  INDEX `fk_language_has_User_User1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_language_has_User_language_idx` (`language_id` ASC)  COMMENT '',
  CONSTRAINT `fk_language_has_User_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `mydb`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_language_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`competence` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TINYTEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competence_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`competence_has_User` (
  `competence_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`competence_id`, `user_id`)  COMMENT '',
  INDEX `fk_competence_has_User_User1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_competence_has_User_competence1_idx` (`competence_id` ASC)  COMMENT '',
  CONSTRAINT `fk_competence_has_User_competence1`
    FOREIGN KEY (`competence_id`)
    REFERENCES `mydb`.`competence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competence_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`call` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type` ENUM('audio', 'video') NOT NULL COMMENT '',
  `strat` DATETIME NOT NULL COMMENT '',
  `end` DATETIME NULL COMMENT '',
  `amount` DOUBLE NULL COMMENT '',
  `sender` INT NOT NULL COMMENT '',
  `receiver` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `sender`, `receiver`)  COMMENT '',
  INDEX `fk_call_User1_idx` (`sender` ASC)  COMMENT '',
  INDEX `fk_call_User2_idx` (`receiver` ASC)  COMMENT '',
  CONSTRAINT `fk_call_User1`
    FOREIGN KEY (`sender`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_User2`
    FOREIGN KEY (`receiver`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`balance` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `amount` DOUBLE NOT NULL COMMENT '',
  `depositedate` DATETIME NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  INDEX `fk_balance_User1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_balance_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
